### ISSUE TITLE
Metric evaluators to implement

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#11]
This issue is a hub for metric implementations, drawn from those covered in [these slides](https://docs.google.com/presentation/d/1fNMNCLeBjR4nLcrApMqtpvMdxnQaGLeoBQTst9QDM-k/edit?usp=sharing).  In particular, I want to make sure we consider the following:

- [x] log-loss
- [x] Brier score
- [ ] At least one AUC of a deteministic metric

Please leave a comment here when you start writing a module for a metric.

EDIT: Please implement metrics as subclass instances of `metric.py` [here](https://github.com/aimalz/proclam/tree/issue/12/infrastructure/proclam/metrics).

**Comment by aimalz** [comment]
I'll implement the log-loss.

**Comment by reneehlozek** [comment]
see the initial brier score coded in https://github.com/aimalz/proclam/tree/renmetric

**Comment by aimalz** [comment]
Excellent work @reneehlozek!  Feel free to start a pull request whenever you're ready.

**Comment by reneehlozek** [comment]
I think I'll implement one or two more @aimalz just so see where we are (I'll try one that only does one class) and then go ahead :)

**Comment by tallamjr** [comment]
I'll have a look into this

**Comment by aimalz** [comment]
This issue is stale, so I'm closing it and make a new one for the last item to tie in to #10 and #20.
