### ISSUE TITLE
Expand pipeline notebook diagnostics

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#18]
What diagnostics of the metric do we want to look at, and how?  The pipeline notebook should loop over all combinations of truth, classifier, and metric, and then print results to a file and make some kinds of diagnostic plots.

**Comment by aimalz** [comment]
@reneehlozek I think we're almost ready for a pull request on the [`demo_notebook`](https://github.com/aimalz/proclam/blob/demo_notebook/metrics_evaluation.ipynb) branch.  It still needs to incorporate @Andromedanita's mock classification results, but other than that, it seems to be in reasonable shape.  What do you think of the actual tests/plots?  Is anything obviously missing?

**Comment by Andromedanita** [comment]
@aimalz  I have already added the code to save the predictions into csv files in the demo_notebook branch. Is there anything else I need to add?

**Comment by aimalz** [comment]
I think this has largely been addressed since we moved on from the demo, so I'm closing this issue.
