### ISSUE TITLE
Confusion matrix-based classifier

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#19]
@gnarayan I'm splitting this from #4 because it's really an infrastructure issue rather than a science issue.  

We want a `classifier` subclass that takes in a confusion matrix and true classes to produce per-object classification probabilities, which may address the distinct cases of systematics from #4 via simply inputting different confusion matrices.

**Comment by juramaga** [comment]
I can work on this next if no one is doing so.

**Comment by aimalz** [comment]
That would be great, thanks!

**Comment by juramaga** [comment]
I have some code that takes the true classes and an arbitrary confusion matrix, then for each item in the truth table it reads the corresponding column of the confusion matrix and outputs that column as the classification probabilities for each item. Is that what we want, or were we thinking of something a bit more complex?

**Comment by aimalz** [comment]
I think we can merge that in for now, but we ultimately might need something a little more sophisticated, because using the appropriate row (I'm going by the standard I used in [slide 4 here](https://docs.google.com/presentation/d/1fNMNCLeBjR4nLcrApMqtpvMdxnQaGLeoBQTst9QDM-k/edit?usp=sharing) though it might be a column in your implementation) would basically have each object classified with probabilities that are exactly equal to the average classification probabilities given the truth.  I can think of a few ways to perturb this to get more realistic classification probabilities over the whole set and still satisfy the confusion matrix constraints, but I don't know which would be preferred from a science perspective.  Perhaps @gnarayan can weigh in.

**Comment by juramaga** [comment]
I see your point. I'll experiment with some perturbations as we discuss it.

**Comment by juramaga** [comment]
Ok, I added some Gaussian perturbations to the CM probabilities. Maybe not the best approach, but at least better than just the exact probabilities from the matrix.

**Comment by aimalz** [comment]
This has been resolved by #22.  Great job, @juramaga!
