### ISSUE TITLE
Deterministic metric utilities

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#20]
We want to try some AUC-based metrics (enabled by #10), which are really a function of deterministic metrics evaluated at probability thresholds.  The basic deterministic metrics are the true and false positive and negative rates, and they can be combined into the more complex deterministic metrics that are building blocks for the PRC/ROC/DET.  (For some context, see the [slides](https://docs.google.com/presentation/d/1fNMNCLeBjR4nLcrApMqtpvMdxnQaGLeoBQTst9QDM-k/edit?usp=sharing) from the SLAC meeting.)  If these were simple utility functions in the `metrics` directory, we could share them among the different base metrics that we'd like to test in the form of an AUC.  

@tallamjr This might be a better place to start than #11.  

EDIT: To clarify, I think there are a few different utility functions to implement here.

1. [x] A function to convert probabilistic classifications to deterministic classifications under a given probability threshold.
2. [x] A function to calculate the true/false positive/negative counts/rates given a set of deterministic classifications and the true classes.
3. [x] A function to produce the true/false positive/negative counts/rates (and their relevant combinations) at many probability thresholds.
4. [x] A function to take the area under a specified curve given its (x, y) pairs. (This is #10.)

These functions could be shared among the PRC, ROC, and DET.

**Comment by aimalz** [comment]
I think @juramaga started on item 3 in the `rafmetric` branch so am assigning this issue to him as well.  All these functions should live in a `util.py` file in the `metrics` directory so they can be shared among many `metric` sub-classes.

**Comment by juramaga** [comment]
I just sent a pull request to add an utility function corresponding to item 2 above. I need someone to review it and test it to make sure it is doing the right thing.

**Comment by aimalz** [comment]
Awesome @juramaga, we're halfway there! @djones1040, I think the last two parts will be a lot easier given the new functionality in `proclam.metrics.util`.

**Comment by aimalz** [comment]
This has been addressed by #80.
