### ISSUE TITLE
Infrastructure for ingesting real classifier output

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#25]
As was discussed on today's call, we may have access to some real classification submissions and their corresponding truth tables.  We'll need some infrastructure to read in this data and convert deterministic classes to probabilistic classes.  This functionality can be implemented in a `util` module in the `classifiers` directory.

**Comment by Andromedanita** [comment]
I'd like to work on this @aimalz

**Comment by reneehlozek** [comment]
I've added some functionality (very clunkily) through https://github.com/aimalz/proclam/pull/27 for

**Comment by aimalz** [comment]
#27 has an example of this in `pipeline_sandbox.ipynb`.  ~~Do folks think we need a built-in module, say `proclam.classifiers.FromFile`/`proclam.simulators/FromFile` or is implementing it in the pipeline notebook good enough?~~  I think I answered my own question; if we want the pipeline to have some kind of loop over metrics/classifiers that will use the real data examples, it should be built-in, so this issue still needs a little more work before it can be closed.
