### ISSUE TITLE
pipeline notebook fails on master on brier on py3

### ISSUE THREAD

**Issue by rbiswas4** [aimalz/proclam#26]
This is due to import lines.

**Comment by aimalz** [comment]
Huh, for me it works on both 2.7 and 3.4.  What errors are you getting and on what lines?

**Comment by rbiswas4** [comment]
Sorry. 
On master : 1dc24c6
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-8c4f2b01ee7f> in <module>()
----> 1 import proclam
      2 from proclam import *

~/doc/projects/DESC/proclam/proclam/__init__.py in <module>()
      4 from .classifiers import classifier
      5 from .classifiers import *
----> 6 from .metrics import metric
      7 from .metrics import *

~/doc/projects/DESC/proclam/proclam/metrics/__init__.py in <module>()
      2 from . import metric
      3 
----> 4 from . import brier
      5 from . import logloss

~/doc/projects/DESC/proclam/proclam/metrics/brier.py in <module>()
      5 import numpy as np
      6 
----> 7 from util import truth_reformatter
      8 from metric import Metric
      9 

ModuleNotFoundError: No module named 'util'```
python version : 3.6.2

**Comment by aimalz** [comment]
Interesting, you're right that it shouldn't work on my end either.  I added the import of `util` to `proclam/metrics/__init__.py`.  Could you try pulling and running it again?  Thanks.

**Comment by juramaga** [comment]
Same happened to me a few days ago. I had to manually import the util.py module from a local directory for it to work. Should have reported.

**Comment by rbiswas4** [comment]
No. That failed too. 

```
...
~/doc/projects/DESC/proclam/proclam/metrics/brier.py in <module>()
      5 import numpy as np
      6 
----> 7 import util
      8 from util import truth_reformatter
      9 import metric
```
I think the problem is that importing  a filename does not do much for you. So, instead of this, you could do:
```
from .util import truth_reformatter
from .metrics import Metric
``` 
would do it.

Python package management works in more ways than one, and I don't really claim to know all of the ways, so it is possible that there is a way that these would work with slight modifications of a different kind. But, one way which works well for me is to think of imports as importing python objects (classes, functions, etc.) but not modules/files.  Accordingly, I could do what I said above.  In fact, given that you want to keep the metrics, classifiers and  simulators separate, perhaps what would be easy is to write in `__init__.py`  within say the `metrics` sub-package, 
(for each module in the package (eg. metrics), we could do
: 
```
from .module import *
```
This will mean we can import every class or method in `metrics`  as `proclam.metrics.method`.
Additionally, each module should have a line (after `from __future__ import absolute_import`)
```
__all__ = [imports]
```
where all objects meant to be imported are included in the sequence `[imports]`
. 

For imports within modules (like the ones that set this off):
```
from . import method
```
or if we really want to import something not included in `__all__`, we can use ```from .module import method```

**Comment by aimalz** [comment]
I'll admit I'm clueless when it comes to the differences between Python 2 and 3 and seem to have messed this up, although I'm not sure why it works for me locally.  The `classifiers` and `metrics` (and `simulators`) sub-modules should each have their own `__init__.py` (and `util.py`) but if I made an error in one then I probably made an error in all of them.  Regardless, I've changed the imports in `brier.py` according to your first suggestion, so it now matches the imports in `logloss.py`.  Can you pull and let me know if it's still broken?  If it fails, could you make a patch and pull request?  Thanks.
