### ISSUE TITLE
Real classifier systematics

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#31]
It would be valuable to test our metrics on confusion matrices and/or real classification probabilities or deterministically predicted classes (plus true class assignments), of any set of transient types.  @reneehlozek started this in #27, and @AshishMahabal has committed to continuing it.  

GitHub has a limit on storage space, so please put any files in a public place on the web where the pipeline notebook can access them, especially if they're larger than 1 MB.  If for some reason you can't do this, contact me and we'll work something out. 

The file format [here](https://github.com/aimalz/proclam/tree/master/examples) would be best, but it's not a dealbreaker.  If the files are not straightforward plaintext, please include a demonstration of how to read in the data in `pipeline_sandbox.ipynb` or provide a README with instructions.

**Comment by AshishMahabal** [comment]
A CSV gist containing a confusion matrix
https://gist.github.com/AshishMahabal/04933628b6cb2b4d3eba412235344c59
