### ISSUE TITLE
First draft of paper

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#35]
This is an issue (and corresponding branch) for discussing the PLAsTiCC metrics paper.  I'll use this space to announce major updates to the draft.

**Comment by aimalz** [comment]
@reneehlozek brought up a good point about authorship.  If you've been involved and I've forgotten your name on the draft, please speak up!

**Comment by juramaga** [comment]
I am happy to contribute with a few paragraphs in the Weights subsection. Will coordinate with @aimalz

**Comment by Andromedanita** [comment]
@aimalz  I can also write a few sentences for the various confusion matrices I coded up.

**Comment by aimalz** [comment]
Thanks @juramaga @Andromedanita @reneehlozek!  I've updated the draft [here](https://github.com/aimalz/proclam/tree/issue/35/paper/desc_note), including adding (very unpolished versions of) most of the figures, aside from a few I haven't made yet.  The sections are also now in different files, which should simplify editing.

@juramaga, It would be great if you could fill in some text about the weighting scheme in [`methods.tex`](https://github.com/aimalz/proclam/tree/issue/35/paper/desc_note/methods.tex) covering what concerns it addresses, the anticipated impact compared to equal weight per object in a class and equal weight per class, and how these specific weights were derived.

@Andromedanita, I left [`data.tex`](https://github.com/aimalz/proclam/tree/issue/35/paper/desc_note/data.tex) wide open for you.  Do you think the subsubsections under "Mock Classifier Systematics" are the right ones to highlight?  I was thinking of having one or maybe two paragraphs for each, and possibly combining a few of them for brevity.

@reneehlozek, I included the results from your mysterious dataset, but the paper will probably require some actual explanation.  Would you mind adding whatever information that will publicly available to [`data.tex`](https://github.com/aimalz/proclam/tree/issue/35/paper/desc_note/data.tex)?
