### ISSUE TITLE
Limiting Cases of LogLoss

### ISSUE THREAD

**Issue by rbiswas4** [aimalz/proclam#45]
For a perfect classifier, LogLoss should return 0 or (epsilon) on a numerical computation for each sample. When I have checked this using `proclam`, I do recover the correct limiting value.  So, I think the code is actually correct.

However, in the nice `main.ipynb` notebook, the plots that are showing Brier and LogLoss values for a number don't show this: the values are much larger O~1 floats or 1. I am guessing some ordering or values are mixed up.

**Comment by rbiswas4** [comment]
@aimalz I found the reason why the Perfect `LogLoss` returns large values rather than `epsilon`. 

In the notebook `main.ipynb`: 
```
plasticc['probs'] = {}
for cc, name in enumerate(plasticc['names']):
    code = proclam.classifiers.FromCM()
    probs = code.classify(plasticc['cm'][name], truth, other=False)
    plasticc['probs'][name] = probs
```
is used to go from the confusion matrix to a realization of probabilities, by drawing from a Cauchy distribution. If you really want to keep this perfect, you need to use `delta = 0.0` to set this random variable to 0. Then it works and gives `epsilon`! How you want to fix that in the code (ie. just set delta = 0. for the case where things are perfect ?) is upto you.

**Comment by aimalz** [comment]
@rbiswas4 Ah, yes, you've found it!  ~~I'd meant to enable setting the perturbing factor parameter(s) of `proclam.classifiers.FromCM.classify()` but hadn't gotten around to it, and it appears that it was much more important than I'd anticipated.  I'll make a patch for that ASAP and ask you to review it.~~ Whoops, I see I'd already implemented it the way I'd intended.  I'm just going to fix it in the notebook as you suggest.
