### ISSUE TITLE
Feedback on first draft of paper

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#49]
The first draft of #35 / #48 isn't, in my opinion, ready for prime time, yet here it is, under review.  This issue can be closed when feedback from the following people is integrated into the paper:

* [x] @Andromedanita (with substantial additions to Introduction)
* [x] @AshishMahabal (with substantial additions to Discussion) 
RH: This has largely been tackled **except:** 
 - the Matthews coefficient stuff
 -  KLD stuff needs to be checked/fixed. 
 - Discussion of Brier score with two classes needs to be done.
* [x] @DoctorLobster (with substantial additions to Data)
@reneehlozek has edited the text and the code, but the KLD stuff needs to be fixed/checked
* [x] @emilleishida 
* [x] @lgalbany
* [x] @michellelochner (with substantial additions to Results) [RH: mostly addressed, might need iterating on some text in new version]
* [x] @RickKessler [RH has worked on intro comments, and up to section 2.3]
* [x] @tloredo (with substantial additions to Conclusion) [RH: mostly addressed/commented on but will definitely need a reread of new version]

I'll add more people as comments trickle in, up until the first round of internal review is complete, at which point my plan is to work, with help from anyone who's interested, on incorporating comments from both the review committee and PLAsTiCC folks.

**Comment by reneehlozek** [comment]
I think these first comments can be closed now - but I'll leave that to @aimalz to confirm!

**Comment by aimalz** [comment]
Oh, wow, thanks @reneehlozek for getting through the rest of them!  I guess we can close this issue now.
