### ISSUE TITLE
Update how mock probability submissions are generated from pseudo-confusion matrices

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#50]
The most serious comment about the paper that came up in #49 was the hack-y way `proclam` generates mock probability vectors from the pseudo-confusion matrices (pending a new name), a procedure implemented in [`proclam/classifiers/from_cm.py`](https://github.com/aimalz/proclam/blob/master/proclam/classifiers/from_cm.py).  To get _p(class | true class)_, we start by selecting the row _CM\_true class_ of the pseudo-confusion matrix corresponding to the true class.

The current algorithm adds small nonnegative numbers (from a half-Cauchy distribution) to the elements of _CM\_true class_ and divides the vector by the sum of its elements so it normalizes to 1.

If I understand correctly, @DoctorLobster's [proposed algorithm](https://drive.google.com/open?id=12UebuqixlcgAg65K6QNkTV9s2Ttn68pd) is to draw the entire _p(class | true class)_ vector from a Dirichlet distribution about _CM\_true class_ because that's actually well-motivated and doesn't require a kludge to enforce non-negativity and normalization.

This issue can be closed when `from_cm.py` uses the new, Dirichlet-based procedure.

**Comment by reneehlozek** [comment]
This has been done in proclam/classifiers/from_cmdm.py, and changes to the text have been made. This needs to be checked by e.g. @DoctorLobster @aimalz
