### ISSUE TITLE
Fix the link to organizing document

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#6]
@rbiswas4 has volunteered to fix @aimalz's blunder with the organizing document in the readme (and elsewhere).

**Comment by rbiswas4** [comment]
@aimalz I have created a version of the google doc. But I realize I am wrong (or at least cannot figure out a way of linking a specific version to the github page, which I thought we could do. Sorry!

Now, I have forgotten your argument of wanting to keep a separate copy of the document in the github .... 
- was it that you did not want someone to just edit it (we could freeze the edits and only allow comments/suggestions)
- Or keep a downloaded copy of the document (in a particular version) on github.

If you have a preference or a different suggestion I can do that.

**Comment by aimalz** [comment]
@rbiswas4 I was thinking of the first issue about non-PLAsTiCC people deleting the content (not that it would be gone, but it would be a hassle to revert to a previous version) and didn't want to make it comment-only to avoid manually giving write access to everyone on the PLAsTiCC team if we want to continue the discussion there.  We can definitely dump a PDF onto GitHub that we occasionally update.  (I bet there's a way to make a Google Doc automatically sync to GitHub, but it's probably not the best use of my time to figure it out.)

**Comment by rbiswas4** [comment]
@aimalz Given that I could not find out very quickly, and don't want to keep trying, it seems like keeping the download is probably best. But it may also help to mention version names in github issues/etc when refering to google docs, because these could change.
