### ISSUE TITLE
Paper Feedback Round 2: @michellelochner

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#63]
I'm seeking volunteers to implement the changes that are not tagged with my name. If you'd like to help, please make a branch, leave a comment on this issue with a link to the branch, check off boxes in this issue as you go, and make a PR as soon as you've gotten through everything you wanted to take on. Thank you!

- [ ] I'm not sure the probabilities coming out machine learning classifiers can be viewed as true posterior probabilities. I know that's what we'd like them to be (probability of class given the data) but all the classifiers operate by maximising some cost function, the parameters "C" are never marginalised over and the cost function is rarely something that actually resembles a likelihood (it's usually the accuracy). The probability that comes out of an ML algorithm may conceptually correspond to a posterior, but I think the actual stuff going on under the hood is enough to make us good Bayesians cry. I don't think it's a major point, 99% of readers won't pick up on it, but it might be worth adding a sentence of something to the effect of "we recognise that the probabilities that come out of ML aren't calibrated and aren't Bayesian but for the purposes of designing metrics and our tests, it's worth thinking about them as if they are" for the handful of people who might be sticky about this (which thinking about it, might only be me... :P). @aimalz

- [x] Top of page 3: I know I've mentioned ROC curves a few times, but I can guarantee that anyone from the Kaggle community will be confused as to why we don't use them, since they do incorporate probabilities (and the "only by reducing class probabilities to deterministic labels via evaluation at different cutoffs" doesn't really apply because the choice of thresholds over which to make the curve makes very tiny perturbative changes to the AUC). Your statement of "many such metrics are restricted to binary classifications" exactly describes why we shouldn't use ROC curves, and I feel for the machine learning community, adding a "such as the commonly used ROC curves <reference>" would easily answer the question many enthusiastic Kagglers would immediately have. 

> I very much want to include the ROC/AUC in this paper!  But I've been urged to not add new material since before I even got your results that included values for your classifiers, so I've refrained from adding it.  There are still comments in the draft for what would be Section 3.1.2, to discuss the ROC/AUC as an adaptation of a deterministic metric. --@aimalz

- [x] Sorry I know it's a bit late for notation issues so I understand if you ignore this, but I think rather than m' and m_hat, where it's hard to remember which is which, you might consider m_t for "true" and m_p for "predicted". It might improve readability. 

> Sorry, it is a bit late for it, and I think the "hat" notation for estimated values is fairly standard so perhaps it's not so bad.  --@aimalz

- [x] Figure 3 (I'm sure you know the label fontsizes need to be fixed) - This figure is somewhat confusing... I think (after staring at it for quite a while) I understand what you're trying to show but it's quite hard to tell at a glance. Is it supposed to be like you have a different type of classifier for each class? Like it gets class 1 perfect but class 5 is always subsumed? I really, really like it as an illustration but there's a lot of information there to unpack! Can you maybe clump the classifier types together in the second plot to see the trends and maybe make it more obvious those are random draws (in the second panel)? 

> @aimalz, I have added some description to the text to help with this, but it may be that rather than having multiple "draws" of the base matrix, we only have one so that folks don't get confused. Also, I'd remove the numbers on the LHS, I think the stars are enough and the numbers make it a bit confusing.

- [x] Line 395 - Maybe implying a star can explode several times is a bit of a stretch. :) Maybe rather use the words "can emit many outbursts" or "flare up many times" or something. 

- [x] Around line 453, I wonder if it isn't worth adding a footnote about what the Hubble diagram is for the benefit of readers who aren't cosmologists (and indeed the few who may not even be astronomers). 

- [x] I think it's worth adding to footnote 9: "The classifiers of Lochner et al. (2016) are indeed probabilistic but are reduced to confusion matrices via deterministic labels (by assigning the class label according to the highest probability) for this visualization and the science-motivated metric..."

- [x] Probably worth adding that we used the second release of simulations that came out after the challenge, since they had several bugs fixed. And maybe everywhere you say "applied to the SNPhotCC dataset" you could say "applied to the SNPhotCC second release dataset". Also might be worth pointing out these were done with a representative training set, not the original training set, although again that's a fairly technical point.

- [x] I like the acronyms for all the classifiers and features, but we used Boosted Decision Trees, not boosted random forests (which I don't think exist?) 

> Ha, when I was given files with those names, I thought, "Huh, I've heard of Boosted Decision Trees but not Boosted Random Forest, must be a new thing @michellelochner invented."  That was the name of the directory containing that data, as given to me at the PLAsTiCC workshop at NYU, but I've fixed it now.  --@aimalz

- [x] I wonder if it's worth mentioning that the template features may be cleaner (at least for Ia's) because they're drawn from the same model the data was made with? 
> hmmm I'm not sure about if this will just make things more confusing since it mixes classifiying with generating? @reneehlozek

- [x] Line 666 (did you do this on purpose?) - at first I thought you were repeating yourself, can we please write this differently so it's not the repetition of the same sentence with subtle differences... Maybe bullet points? Use emphasis to highlight some words? Something that doesn't make me feel like there's something wrong with my eyes.

- [x] Figure 5 - I found it quite hard to get any real information out of this figure, other than if you add a systematic you get a worse score. In particular the last panel has so much on it that it's quite confusing. Am I right that there are nine different combinations on that last panel? Is the main conclusion of this plot that the logloss is more sensitive? I'd suggest either making the plot more clear (you could give each baseline a different colour bar, you could maybe just choose one baseline and three systematics, you could choose two baselines and two systematics etc.) or else just highlight in the caption what the main take-away from this. @aimalz

> in the interim I've made changes to the figure caption --@reneehlozek

- [x] Personally I liked the plot showing FoM vs. logloss and brier for the SNPhotCC results (but naturally I'm biased) more than just the ranking (or in addition to) simply because we're visual creatures and plots are easier to read than tables. It is also a natural question to ask how a deterministic metric stacks up against a probabilistic one so it's interesting to see the comparison. 

> yes, I agree that I liked the figure! --@reneehlozek

- [x] Line 776 - I'm not actually sure I agree with the statement that decisions for follow-up would require a deterministic metric. I mean, yes ultimately in the sense of "do we follow it up or not" but basically what you'd want is to come up with a ranked list of objects with the highest scientific relevance and then just work your way down as much of the list as possible. The per-object scores we've got here are perfect for this, particularly because you can adjust the weights according to scientific preference so I'd go beyond what you say in your footnote and still say these metrics are important for follow-up decisions too. 

- [x] Line 839 - "This version of PLAsTiCC implements quality cuts to homogenize difficulty to some degree" -> doesn't this count as privileged information??? I don't think we technically should know this.

> Someone other than me added that in, and since it's here, it's public information now.  For what it's worth, I think people will assume that cuts have been made, i.e. we won't be classifying lightcurves that wouldn't have made LSST's quality cuts anyway. --@aimalz

- [x] Line 105 presumably should be "common classes"
- [x] Line 448 - Full stop after SNIbc before the
- [x] Line 665 "each baseline" not baselines
- [x] Lines 683 - "for all weights"
- [x] Line 783 - "optimally" -> "optimal"
- [x] line 806 - "we'll have" -> "we would have"
- [x] Line 823 - "the sparsity and regularity of observations" -> suggest "the sparsity and irregularity of observations" (since the one is in the negative)
- [x] Line 833 - value appears twice
- [x] Line 847 - " the investigative approach" -> " an investigative approach"
- [x] Line 892 - "orsiginal" -> "original"
- [x] You only use "T&V" three times and I wonder, since it's maybe not a super common acronym, if it isn't worth just spelling out transient and variables each time

**Comment by tallamjr** [comment]
Fixed typos and included some suggestions relating to lines 833, 847 & 892

**Comment by MichelleLochner** [comment]
@aimalz I'm getting to this now (sorry as usual..)

* ROC curves -> I'm literally just suggesting adding "such as the commonly-used ROC curves [citation]" I'm not sure adding 7 words counts as new material... ;) Anyone who doesn't know what those are will ignore this statement and everyone who knows what they are will think "oh so that's why they don't just use ROC curves". (I can't seem to get at the pdf so I don't know if you've made this change but from the comment it didn't sound like it).

*  I wonder if it's worth mentioning that the template features may be cleaner (at least for Ia's) because they're drawn from the same model the data was made with? - I think I agree with Renee actually. This is probably more confusing than helpful.

* Boosted Random Forests ---- hahaha you're completely right. I totally did invent that name. I think it might actually be a relic from an intern... Please change to boosted decision trees :D

* I'd really like to have a look at the updated figure 3 & 5 but I'm on a new laptop and am having issues with this "mkauthlist" thing which always seems to crop up (probably doesn't play nicely with anaconda or something). @aimalz or @reneehlozek can you please just email me the pdf to save time?
