### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JohannesBuchner** [aimalz/proclam#75]
Dear all,

I was wondering what license is proclam code under? I would like to reuse the logloss implementation (although there seem to be differences to the challenge specs in terms of class weights).

Cheers,
               Johannes

**Comment by aimalz** [comment]
@JohannesBuchner Thanks for bringing this up.  Somehow when the project started we must have gotten so excited that we forgot to make a license?  In any case, it's being finalized in #76 and will be settled by the end of the week.  In the interim, I'm making the executive decision that you may assume the standard MIT license for now, but please check back next week to confirm just in case.
