### ISSUE TITLE
Generating true classes to test metric sensitivity to class imbalance

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#8]
We'll need to check on how sensitive each metric is to the imbalance in number of objects in each class.  To do this, there should be a script for generating true classes for a variable set of N objects and possibly a variable number M of classes as well.  

EDIT: Please implement modules that make different "truth" sets as `simulator` subclasses, modeling after `uniform.py` found [here](https://github.com/aimalz/proclam/tree/master/proclam/simulators).

**Comment by aimalz** [comment]
I'll start this off by making a jupyter notebook with vanilla version for an equal distribution of classes.

**Comment by aimalz** [comment]
As was mentioned in the call, it should be sufficient to set the number of members of each type as Poisson draws about mu = 10<sup>6</sup>, 10<sup>5</sup>, 10<sup>4</sup>, 10<sup>3</sup>, 10<sup>2</sup>, 10<sup>1</sup>.  It would be great if someone could just write a little wrapper around [`scipy.stats.poisson`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.poisson.html) to do this.  

Another way to do it would be to take N<sub>classes</sub> draws _x_ from a continuous uniform distribution \[0, 6\] and set the number of members of each class to be the nearest integer to 10<sup>_x_</sup>.

**Comment by juramaga** [comment]
For the unbalanced distribution of classes, do we want the exact number of classes and items to be a fixed parameter according to which the relative number of objects in each class will be normalized? Or do we want the total number of objects in the simulated truth table to be set by the number of objects in each class, as given by, for example, poisson draws?

**Comment by juramaga** [comment]
Here is some code for an unbalanced simulator of truth tables:

https://github.com/aimalz/proclam/blob/rafmetric/proclam/simulators/unbalanced.py

**Comment by aimalz** [comment]
Closed by #21
