### ISSUE TITLE
New written content describing new metrics

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#86]
Describe the additional metrics in subsections of Section 3 (Methods):

Deterministic metrics, with subsubsections for:
- [ ] ~~Accuracy~~
- [ ] F1 score @mi-dai 
- [ ] ~~Matthews Correlation Coefficient~~

Probabilistic adaptations of deterministic metrics, with subsubsections for:
- [ ] ~~ROC AUC~~
- [ ] ~~PRC AUC~~

**Comment by aimalz** [comment]
The deterministic metrics are currently described briefly in section 3.1, but the revision can have section 3.1 just be "Deterministic metrics" and then have Accuracy, F1 Score, and Matthews Correlation Coefficient in a new section 3.1.1 "Classic deterministic metrics", the AUC metrics in a new section 3.1.2 "Probabilistic adaptations of deterministic metrics", and the science-motivated deterministic metrics that currently comprise section 3.1 moved to a new section 3.1.3.

**Comment by mi-dai** [comment]
@aimalz is the latest version of the paper in master? or where should I pull it from?

**Comment by aimalz** [comment]
@mi-dai I haven't updated the paper in a branch yet, so working from master is the correct choice.

**Comment by aimalz** [comment]
The paper has now been accepted for publication so we no longer need this issue.  (-:
