### ISSUE TITLE
Multi-class metric averaging per object vs. per class

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#9]
We should test both weighting schemes (equal weight per class and equal weight per object) for constructing multi-class metrics from the base components of single-class metric.

**Comment by aimalz** [comment]
This could be done with a pair of simple utility functions in the metrics directory.  Both would take in a metric value for each object that was classified.  The equal-weight-per-object metric would simply average all input metric values.  The equal-weight-per-class metric evaluator would also take the truth table, and it would average the metric values within each class and then average the class-averaged metric values.  Then the metric subclasses could call these functions depending on the desired multi-class combination strategy.

**Comment by AshishMahabal** [comment]
Alex, what is the format in which the metric values will be provided? I could not find those details in the metrics directory.

**Comment by aimalz** [comment]
Ultimately, for the competition on Kaggle/RAMP, the metric needs to be a single scalar.
